export class Review {
  id: number;
  owner: string;
  created_on: string;
  modified_on: string;
  modified_by: string;
  target_audience_nonrel_reason: string;
  key_behaviour_areas_of_concern: string;
  good_to_have_information: number;
  good_to_have_information_representation: object;
  target_audience: object;
  key_behaviour: object;
  key_behaviour_representation: object;
  target_audience_representation: string;
  areas_of_concern1: string;
  related: number;
  target_audience_nonrep_reason: object;
  areas_of_concern: object;
  good_to_have_norep_reason: object;
  key_behaviour_practice: object;
  key_behaviour_no_rep_reason: string;
  key_behaviour_practice_correct: string;
  key_behaviour_no_practiced: number;
  key_behaviour_nopracticed_concern: object;
  good_to_have_information_norep_reason: object;
  evaluation_criteria: object;
  pan_india: object;
  apply_to_specific_community: object;
  submission_id: object;
  status:[''];
  review_result:[''];
  review_score:[''];
}
